export const memories = [
  { text: "Héloïse", type: true },
  { text: "Anxiety", type: false },
  { text: "The day I met my wife", type: true },
  { text: "First skateboard", type: true },
  { text: "Mountain trip", type: true },
  { text: "Football game", type: true },
  { text: "My street", type: true },
  { text: "My dog", type: true },
  { text: "Sick of school", type: false },
  { text: "Dreaming in class", type: true },
  { text: "Fighting", type: false },
  { text: "Seeing Trees through the window", type: true },
  { text: "18th birthday", type: true },
  { text: "The forest", type: true },
  { text: "I asked her hand", type: true },
  { text: "Out of Breath", type: false },
  { text: "Fear", type: false },
  { text: "Unease", type: false },
  { text: "Choking", type: false },
  { text: "Panic", type: false },
  { text: "Anxious", type: false },
  { text: "Alarm", type: false },
  { text: "Distress", type: false },
  { text: "Alone", type: false },
  { text: "Darkness", type: false },
  { text: "Do I Belong?", type: false },
  { text: "Agoraphobia", type: false },
  { text: "Society", type: false },
  { text: "Capitalism", type: false },
  { text: "Douglas Fir", type: true },
  { text: "Hiking around Gavarnie", type: true },
  { text: "A damn good cup of coffee", type: true },
  { text: "Cherry Pie", type: true },
  { text: "Twin Peaks", type: true },
  { text: "She said yes", type: true },
];
